### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by amongususus123** [X-ProxyTech/Youtube-Proxy#3]
![image](https://github.com/user-attachments/assets/4571e3ec-91bf-49d5-9a92-e38abc7c2348)

**Comment by Searchcat37** [comment]
I don't know how you found this, but this should have been archived when Heroku removed their free plan. If you want the original repository, it can be found here.  [https://github.com/dmhacker/dmhacker-youtube](https://github.com/dmhacker/dmhacker-youtube)

**Comment by amongususus123** [comment]
lmao thanks
